package com.rumpilstilstkin.gloomhavenhelper.bd.filler

import com.rumpilstilstkin.gloomhavenhelper.bd.dao.ScenarioDao
import com.rumpilstilstkin.gloomhavenhelper.bd.entity.ScenarioBd
import com.rumpilstilstkin.gloomhavenhelper.domain.entity.PackType

object ScenariosFiller {
    suspend fun fill_v1(
        scenarioDao: ScenarioDao
    ) {
        scenarioDao.insertAll(
            ScenarioBd(
                scenarioNumber = 1,
                name = "Черный курган",
                newScenarios = "2",
                teamAchievement = "Первые шаги",
                monsters = listOf(
                    "Разбойник-страж",
                    "Разбойник-лучница",
                    "Ожившие кости"
                ),
                location = "Мертволесье",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 2,
                name = "Подземное логово",
                newScenarios = "3, 4",
                requirements = "Первые шаги",
                monsters = listOf(
                    "Разбойник-лучница",
                    "Ожившие кости",
                    "Оживший труп",
                    "Главарь разбойников"
                ),
                location = "Мертволесье",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 3,
                name = "Лагерь иноксов",
                newScenarios = "8, 9",
                requirements = "!Сбежавшая торговка",
                teamAchievement = "Планы Джексеры",
                monsters = listOf(
                    "Инокс-стражница",
                    "Инокс-лучник",
                    "Инокс-шаман",
                ),
                location = "Кинжальный лес",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 4,
                name = "Склеп проклятых",
                newScenarios = "5, 6",
                monsters = listOf(
                    "Разбойник-лучница",
                    "Ожившие кости",
                    "Культист",
                    "Земляной демон",
                    "Воздушный демон"
                ),
                location = "Тихая река",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 5,
                name = "Зловещий склеп",
                newScenarios = "10, 14, 19",
                monsters = listOf(
                    "Ожившие кости",
                    "Культист",
                    "Ночной демон",
                    "Огненный демон",
                    "Морозный демон",
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 6,
                name = "Обветшалый склеп",
                newScenarios = "8",
                teamAchievement = "Планы Джексеры, Темная награда",
                monsters = listOf(
                    "Оживший дух",
                    "Оживший труп",
                    "Ожившие кости",
                ),
                location = "Тихая река",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 7,
                name = "Цветущий грот",
                newScenarios = "20",
                requirements = "Возможость улучшений && Сбежавшая торговка",
                monsters = listOf(
                    "Лесной бес",
                    "Пещерный медведь",
                    "Инокс-шаман",
                    "Земляной демон",
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 8,
                name = "Склад мрачной гавани",
                newScenarios = "7, 13, 14",
                globalAchievement = "Сбежавшая торговка",
                requirements = "Планы Джексеры && !Вторжение мертвецов",
                monsters = listOf(
                    "Ожившие кости",
                    "Оживший труп",
                    "Инокс-телохранитель - 1",
                    "Инокс-телохранитель - 2",
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 9,
                name = "Алмазная шахта",
                newScenarios = "11, 12",
                globalAchievement = "Вторжение мертвецов",
                requirements = "!Сбежавшая торговка",
                monsters = listOf(
                    "Гончая",
                    "Вермлинг-разведчик",
                    "Жестокий надзиратель",
                ),
                location = "Сторожевые горы",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 10,
                name = "Измерение силы стихий",
                newScenarios = "21, 22",
                teamAchievement = "Задание демона",
                requirements = "!Портал обезврежен",
                monsters = listOf(
                    "Огненный демон",
                    "Земляной демон",
                    "Солнечный демон",
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 11,
                name = "Площадь Мрачной гавани А",
                newScenarios = "16, 18",
                globalAchievement = "Городское правление: торговцы, Конец вторжения",
                requirements = "!Конец вторжения",
                monsters = listOf(
                    "Ожившие кости",
                    "Оживший труп",
                    "Городской страж",
                    "Городской лучник",
                    "Начальник стражи"
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 12,
                name = "Площадь Мрачной гавани Б",
                newScenarios = "16, 18, 28",
                globalAchievement = "Конец вторжения",
                requirements = "!Конец вторжения",
                monsters = listOf(
                    "Ожившие кости",
                    "Оживший труп",
                    "Культист",
                    "Городской страж",
                    "Городской лучник",
                    "Джексера"
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 13,
                name = "Храм прорицателя",
                newScenarios = "15, 17, 20",
                monsters = listOf(
                    "Каменный голем",
                    "Пещерный медведь",
                    "Оживший дух",
                    "Шипящий дрейк",
                ),
                location = "Сторожевые горы",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 14,
                name = "Ледяная пещера",
                newScenarios = "",
                globalAchievement = "Возможость улучшений",
                monsters = listOf(
                    "Гончая",
                    "Оживший дух",
                    "Морозный демон",
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 15,
                name = "Святилище силы",
                monsters = listOf(
                    "Каменный голем",
                    "Саввас Ледяной шторм",
                    "Воздушный демон",
                    "Морозный демон",
                    "Жнец заразитель",
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 16,
                name = "Горный перевал",
                newScenarios = "24, 25",
                monsters = listOf(
                    "Земляной демон",
                    "Воздушный демон",
                    "Инокс-стражница",
                    "Инокс-лучник",
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 17,
                name = "Затерянный остров",
                monsters = listOf(
                    "Вермлинг-разведчик",
                    "Вермлинг-шаман",
                    "Пещерный медведь",
                ),
                location = "Туманное море",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 18,
                name = "Заброшенная канализация",
                newScenarios = "14, 23, 26, 43",
                monsters = listOf(
                    "Вермлинг-разведчик",
                    "Гигантская гадюка",
                    "Слизь",
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 19,
                name = "Забытый склеп",
                newScenarios = "27",
                requirements = "Возможость улучшений",
                teamAchievement = "Кадило Каменолома",
                monsters = listOf(
                    "Культист",
                    "Ожившие кости",
                    "Оживший дух",
                    "Оживший труп",
                ),
                location = "Вечное болото",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 20,
                name = "Прибежище некромантки",
                newScenarios = "16, 18, 28",
                requirements = "Сбежавшая торговка",
                monsters = listOf(
                    "Культист",
                    "Ожившие кости",
                    "Ночной демон",
                    "Оживший труп",
                    "Джексера",
                ),
                location = "Мертволесье",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 21,
                name = "Дьявольский трон",
                requirements = "Портал обезврежен",
                globalAchievement = "Портал обезврежен, Артефакт: найден",
                monsters = listOf(
                    "Солнечный демон",
                    "Морозный демон",
                    "Ночной демон",
                    "Воздушный демон",
                    "Земляной демон",
                    "Огненный демон",
                    "Архидемон"
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 22,
                name = "Храм стихий",
                newScenarios = "31, 35, 36",
                requirements = "Задание демона || По следам",
                globalAchievement = "Артефакт: найден",
                monsters = listOf(
                    "Ожившие кости",
                    "Культист",
                    "Морозный демон",
                    "Воздушный демон",
                    "Земляной демон",
                    "Огненный демон",
                ),
                location = "Река Змеиный поцелуй",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 23,
                name = "Глубокие руины",
                newScenarios = "26",
                globalAchievement = "Древняя технология",
                teamAchievement = "Путь через руины",
                monsters = listOf(
                    "Каменный голем",
                    "Древняя пушка",
                    "Ожившие кости",
                    "Оживший дух",
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 24,
                name = "Шепчущая галерея",
                newScenarios = "30, 32",
                teamAchievement = "Веление Голоса",
                monsters = listOf(
                    "Когтистый дрейк",
                    "Слизь",
                    "Оживший дух",
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 25,
                name = "Восхождение на Ледяной утес",
                newScenarios = "33, 34",
                teamAchievement = "Предложение дрейка",
                monsters = listOf(
                    "Когтистый дрейк",
                    "Шипящий дрейк",
                    "Гончая",
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 26,
                name = "Древний резервуар",
                requirements = "Подводное дыхание || Путь через руины",
                newScenarios = "22",
                teamAchievement = "По следам",
                monsters = listOf(
                    "Оживший труп",
                    "Слизь",
                    "Ночной демон",
                    "Черный бес"
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 27,
                name = "Зловещий портал",
                requirements = "!Артефакт: потерян && Кадило Каменолома",
                globalAchievement = "Портал обезврежен",
                monsters = listOf(
                    "Ночной демон",
                    "Воздушный демон",
                    "Морозный демон",
                    "Солнечный демон",
                    "Земляной демон",
                    "Огненный демон"
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 28,
                name = "Внешнее капище",
                requirements = "Темная награда",
                newScenarios = "29",
                teamAchievement = "Приглашение",
                monsters = listOf(
                    "Ночной демон",
                    "Оживший труп",
                    "Ожившие кости",
                    "Солнечный демон",
                    "Культист",
                ),
                location = "Кинжальный лес",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 29,
                name = "Обитель Мрака",
                requirements = "Приглашение",
                globalAchievement = "На грани тьмы",
                monsters = listOf(
                    "Ожившие кости",
                    "Оживший дух",
                    "Оживший труп",
                    "Черный бес",
                ),
                location = "Кинжальный лес",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 30,
                name = "Святилище глубин",
                requirements = "Веление Голоса",
                newScenarios = "42",
                teamAchievement = "Голос и скипитер",
                monsters = listOf(
                    "Слизь",
                    "Скрытень",
                    "Невыносимый ужас",
                ),
                location = "Туманное море",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 31,
                name = "Ночное измерение",
                requirements = "Возможость улучшений && Артефакт: найден",
                newScenarios = "37, 38, 39, 43",
                globalAchievement = "Артефакт: очищен",
                monsters = listOf(
                    "Черный бес",
                    "Ночной демон",
                    "Невыносимый ужас",
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 32,
                name = "Ветхая пуща",
                requirements = "Веление Голоса",
                newScenarios = "33, 40",
                monsters = listOf(
                    "Жнец заразитель",
                    "Гигантская гадюка",
                    "Невыносимый ужас",
                    "Черный бес",
                ),
                location = "Вечное болото",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 33,
                name = "Оружейная саввасов",
                requirements = "Веление Голоса || Предложение дрейка",
                teamAchievement = "Сокровище голоса, Сокровище дрейка",
                monsters = listOf(
                    "Саввас Ледяной шторм",
                    "Саввас Поток лавы",
                    "Воздушный демон",
                    "Морозный демон",
                    "Огненный демон",
                    "Земляной демон",
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 34,
                name = "Выжженнная вершина",
                requirements = "Предложение дрейка && !Помощь дрейку",
                teamAchievement = "(-)Предложение дрейка",
                globalAchievement = "Убийство дрейка",
                monsters = listOf(
                    "Когтистый дрейк",
                    "Шипящий дрейк",
                    "Дрейк-патриарх",
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 35,
                name = "Бойницы Мрачной гавани А",
                requirements = "Задание демона && !Портал обезврежен",
                newScenarios = "45",
                teamAchievement = "(-)Задание демона",
                globalAchievement = "Городское правление: демоны, Артефакт: потерян",
                monsters = listOf(
                    "Городской страж",
                    "Городской лучник",
                    "Воздушный демон",
                    "Морозный демон",
                    "Огненный демон",
                    "Земляной демон",
                    "Начальник стражи"
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 36,
                name = "Бойницы Мрачной гавани Б",
                requirements = "Задание демона && !Портал обезврежен",
                teamAchievement = "(-)Задание демона",
                globalAchievement = "Портал обезврежен",
                monsters = listOf(
                    "Городской лучник",
                    "Воздушный демон",
                    "Морозный демон",
                    "Огненный демон",
                    "Земляной демон",
                    "Архидемон"
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 37,
                name = "Гиблая впадина",
                requirements = "Подводное дыхание",
                newScenarios = "47",
                teamAchievement = "Путь через впадину",
                monsters = listOf(
                    "Скрытень",
                    "Невыносимый ужас",
                    "Жнец заразитель",
                ),
                location = "Туманное море",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 38,
                name = "Невольничьи клетки",
                newScenarios = "44, 48",
                teamAchievement = "Помощь Красношипа",
                monsters = listOf(
                    "Инокс-стражница",
                    "Инокс-лучник",
                    "Инокс-шаман",
                    "Каменный голем"
                ),
                location = "Кинжальный лес",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 39,
                name = "Коварная пропасть",
                newScenarios = "15, 46",
                teamAchievement = "Путь через пропасть",
                monsters = listOf(
                    "Пещерный медведь",
                    "Морозный демон",
                    "Шипящий дрейк",
                    "Культист",
                    "Ожившие кости"
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 40,
                name = "Древние защитные механизмы",
                requirements = "Веление Голоса && Сокровище голоса",
                newScenarios = "41",
                globalAchievement = "Древняя технология",
                monsters = listOf(
                    "Пещерный медведь",
                    "Оживший труп",
                    "Лесной бес",
                    "Каменный голем",
                    "Огненный демон"
                ),
                location = "Мертволесье",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 41,
                name = "Вековая гробница",
                requirements = "Веление Голоса",
                globalAchievement = "Голос освобожден",
                monsters = listOf(
                    "Древняя пушка",
                    "Оживший труп",
                    "Оживший дух",
                    "Каменный голем",
                ),
                location = "Мертволесье",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 42,
                name = "Царство Голоса",
                requirements = "Голос и скипитер && !Голос освобожден",
                teamAchievement = "(-)Веление Голоса",
                globalAchievement = "Голос умолк",
                monsters = listOf(
                    "Воздушный демон",
                    "Ночной демон",
                    "Оживший дух",
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 43,
                name = "Гнездо дрейков",
                requirements = "Возможость улучшений",
                globalAchievement = "Подводное дыхание",
                monsters = listOf(
                    "Когтистый дрейк",
                    "Шипящий дрейк",
                    "Огненный демон",
                ),
                location = "Кинжальный лес",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 44,
                name = "Нападение племени",
                requirements = "Помощь Красношипа",
                monsters = listOf(
                    "Инокс-стражница",
                    "Инокс-лучник",
                    "Инокс-шаман",
                    "Гончая"
                ),
                location = "Кинжальный лес",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 45,
                name = "Привал подводных повстанцев",
                requirements = "Городское правление: демоны",
                newScenarios = "49, 50",
                monsters = listOf(
                    "Городской страж",
                    "Городской лучник",
                    "Гончая",
                ),
                location = "Вечное болото",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 46,
                name = "Пик кошмара",
                requirements = "Путь через пропасть",
                newScenarios = "51",
                globalAchievement = "Конец упадка",
                monsters = listOf(
                    "Ночной демон",
                    "Морозный демон",
                    "Воздушный демон",
                    "Саввас Ледяной шторм",
                    "Крылатый ужас"
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 47,
                name = "Логово невидящего ока",
                requirements = "Путь через впадину",
                newScenarios = "51",
                globalAchievement = "Конец упадка",
                monsters = listOf(
                    "Скрытень",
                    "Невыносимый ужас",
                    "Невидящее око",
                    "Жнец заразитель"
                ),
                location = "Туманное море",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 48,
                name = "Тенистая чаща",
                requirements = "Помощь Красношипа",
                newScenarios = "51",
                globalAchievement = "Конец упадка",
                monsters = listOf(
                    "Лесной бес",
                    "Земляной демон",
                    "Жнец заразитель",
                    "Темный всадник",
                ),
                location = "Кинжальный лес",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 49,
                name = "Лагерь повстанцев",
                requirements = "Городское правление: демоны",
                globalAchievement = "Уничтожение порядка",
                monsters = listOf(
                    "Гигантская гадюка",
                    "Городской страж",
                    "Городской лучник",
                    "Древняя пушка"
                ),
                location = "Вечное болото",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 50,
                name = "Призрачная крепость",
                requirements = "Городское правление: демоны && !Уничтожение порядка",
                globalAchievement = "Городское правление: военные",
                monsters = listOf(
                    "Ночной демон",
                    "Солнечный демон",
                    "Земляной демон",
                    "Воздушный демон"
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 51,
                name = "Пустота",
                newScenarios = "96",
                requirements = "Конец упадка",
                globalAchievement = "Конец эпохи Мрака",
                monsters = listOf(
                    "Мрак",
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 52,
                name = "Жуткий погреб",
                requirements = "Личное задание: Последователь зорна",
                newScenarios = "53",
                monsters = listOf(
                    "Шипящий дрейк",
                    "Слизь",
                    "Вермлинг-разведчик",
                    "Вермлинг-шаман",
                    "Оживший труп"
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 53,
                name = "Подвал склепа",
                requirements = "Личное задание: Последователь зорна",
                newScenarios = "54",
                monsters = listOf(
                    "Слизь",
                    "Оживший труп",
                    "Оживший дух",
                    "Ожившие кости",
                    "Гигантская гадюка"
                ),
                location = "Тихая река",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 54,
                name = "Ледяной дворец",
                requirements = "Личное задание: Последователь зорна && Посох Зорна находится в инвентаре",
                monsters = listOf(
                    "Пещерный медведь",
                    "Оживший дух",
                    "Морозный демон",
                    "Жнец заразитель",
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 55,
                name = "Туманные заросли",
                requirements = "Личное задание: Возвращение леса",
                newScenarios = "56",
                location = "Кинжальный лес",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 56,
                name = "Разбойничья пуща",
                requirements = "Личное задание: Возвращение леса",
                monsters = listOf(
                    "Гончая",
                    "Разбойник-лучница",
                    "Когтистый дрейк",
                    "Разбойник-страж",
                ),
                location = "Кинжальный лес",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 57,
                name = "Расследование",
                requirements = "Личное задание: Месть",
                newScenarios = "58",
                monsters = listOf(
                    "Гончая",
                    "Городской страж",
                    "Городской лучник",
                    "Жнец заразитель",
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 58,
                name = "Кровавая хижина",
                requirements = "Личное задание: Месть",
                monsters = listOf(
                    "Земляной демон",
                    "Городской страж",
                    "Черный бес",
                    "Жнец заразитель",
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 59,
                name = "Забытая роща",
                requirements = "Личное задание: В Поисках лекарства",
                newScenarios = "60",
                monsters = listOf(
                    "Гончая",
                    "Пещерный медведь",
                    "Лесной бес",
                ),
                location = "Кинжальный лес",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 60,
                name = "Алхимическая лаборатория",
                requirements = "Личное задание: В Поисках лекарства",
                monsters = listOf(
                    "Гончая",
                    "Гигантская гадюка",
                    "Слизь",
                    "Когтистый дрейк",
                    "Шипящий дрейк",
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 61,
                name = "Исчезающий маяк",
                requirements = "Личное задание: Грехопадение",
                newScenarios = "62",
                monsters = listOf(
                    "Слизь",
                    "Гигантская гадюка",
                    "Морозный демон",
                    "Огненный демон",
                ),
                location = "Вечное болото",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 62,
                name = "Колодец душ",
                requirements = "Личное задание: Грехопадение",
                monsters = listOf(
                    "Оживший дух",
                    "Ожившие кости",
                ),
                location = "Вечное болото",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 63,
                name = "Жерло вулкана",
                monsters = listOf(
                    "Вермлинг-разведчик",
                    "Огненный демон",
                    "Инокс-стражница",
                    "Инокс-лучник",
                ),
                location = "Сторожевые горы",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 64,
                name = "Подводная лагуна",
                requirements = "Подводное дыхание",
                monsters = listOf(
                    "Слизь",
                    "Лесной бес",
                    "Когтистый дрейк",
                ),
                location = "Туманное море",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 65,
                name = "Серная шахта",
                globalAchievement = "Древняя технология",
                monsters = listOf(
                    "Вермлинг-разведчик",
                    "Гончая",
                    "Инокс-шаман",
                ),
                location = "Сторожевые горы",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 66,
                name = "Заводное побережье",
                globalAchievement = "Древняя технология",
                monsters = listOf(
                    "Слизь",
                    "Древняя пушка",
                    "Каменный голем",
                    "Оживший дух"
                ),
                location = "Мертволесье",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 67,
                name = "Мистическая библиотека",
                globalAchievement = "Древняя технология",
                monsters = listOf(
                    "Лесной бес",
                    "Пещерный медведь",
                    "Каменный голем",
                ),
                location = "Восточный тракт",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 68,
                name = "Ядовитая трясина",
                monsters = listOf(
                    "Когтистый дрейк",
                    "Черный бес",
                    "Гигантская гадюка",
                    "Оживший труп",
                ),
                location = "Вечное болото",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 69,
                name = "Колодец несчастий",
                monsters = listOf(
                    "Вермлинг-разведчик",
                    "Вермлинг-шаман",
                    "Лесной бес",
                    "Каменный голем",
                    "Оживший дух"
                ),
                location = "Каменистый тракт",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 70,
                name = "Прикованный остров",
                monsters = listOf(
                    "Ночной демон",
                    "Воздушный демон",
                    "Оживший дух"
                ),
                location = "Туманное море",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 71,
                name = "Подветренное нагорье",
                monsters = listOf(
                    "Шипящий дрейк",
                    "Воздушный демон",
                    "Солнечный демон"
                ),
                location = "Река Змеиный поцелуй",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 72,
                name = "Скользкая роща",
                monsters = listOf(
                    "Слизь",
                    "Гигантская гадюка",
                    "Лесной бес",
                ),
                location = "Мертволесье",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 73,
                name = "Гряда камнепадов",
                monsters = listOf(
                    "Древняя пушка",
                    "Инокс-шаман",
                    "Инокс-стражница",
                    "Инокс-лучник",
                    "Гончая",
                ),
                location = "Сторожевые горы",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 74,
                name = "Торговый корабль",
                requirements = "Морской конвой",
                monsters = listOf(
                    "Разбойник-страж",
                    "Разбойник-лучница",
                    "Скрытень",
                    "Невыносимый ужас",
                ),
                location = "Туманное море",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 75,
                name = "Заросшее кладбище",
                requirements = "Гробокопатели",
                monsters = listOf(
                    "Оживший дух",
                    "Оживший труп",
                    "Ожившие кости",
                ),
                location = "Мертволесье",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 76,
                name = "Улей жнецов",
                requirements = "Храбрость",
                monsters = listOf(
                    "Гигантская гадюка",
                    "Ночной демон",
                    "Ожившие кости",
                    "Жнец заразитель"
                ),
                location = "Сторожевые горы",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 77,
                name = "Хранилище тайн",
                monsters = listOf(
                    "Гончая",
                    "Городской страж",
                    "Городской лучник",
                    "Каменный голем",
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 78,
                name = "Темница жертвоприношений",
                monsters = listOf(
                    "Разбойник-страж",
                    "Разбойник-лучница",
                    "Культист",
                    "Ожившие кости",
                    "Черный бес"
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 79,
                name = "Затерянный храм",
                requirements = "Сомнительный помощник",
                monsters = listOf(
                    "Каменный голем",
                    "Гигантская гадюка",
                    "Предатель",
                ),
                location = "Вечное болото",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 80,
                name = "Цитадель караула",
                monsters = listOf(
                    "Гончая",
                    "Городской страж",
                    "Городской лучник",
                    "Древняя пушка",
                ),
                location = "Сторожевые горы",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 81,
                name = "Храм затмения",
                monsters = listOf(
                    "Ночной демон",
                    "Солнечный демон",
                    "Каменный голем",
                    "Древняя пушка",
                    "Бесцветный"
                ),
                location = "Кинжальный лес",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 82,
                name = "Пылающая гора",
                monsters = listOf(
                    "Земляной демон",
                    "Огненный демон",
                    "Каменный голем",
                ),
                location = "Сторожевые горы",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 83,
                name = "Обитель теней",
                requirements = "Дурное знамение",
                monsters = listOf(
                    "Гончая",
                    "Культист",
                    "Ожившие кости",
                    "Оживший дух",
                    "Огненный демон",
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 84,
                name = "Пещера кристалов",
                requirements = "Дрожь земли",
                monsters = listOf(
                    "Земляной демон",
                    "Огненный демон",
                    "Морозный демон",
                ),
                location = "Медные хребты",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 85,
                name = "Храм солнца",
                monsters = listOf(
                    "Ночной демон",
                    "Солнечный демон",
                    "Гончая",
                    "Черный бес"
                ),
                location = "Сторожевые горы",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 86,
                name = "Разграбленная деревня",
                newScenarios = "87",
                teamAchievement = "Источник отравы",
                monsters = listOf(
                    "Пещерный медведь",
                    "Вермлинг-шаман",
                    "Вермлинг-разведчик",
                    "Скрытень"
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 87,
                name = "Злосчастное побережье",
                requirements = "Источник отравы",
                monsters = listOf(
                    "Скрытень",
                    "Невыносимый ужас",
                    "Слизь",
                    "Черный бес"
                ),
                location = "Бухта торговцев",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 88,
                name = "Водное измерение",
                requirements = "Подводное дыхание && Посох воды",
                monsters = listOf(
                    "Морозный демон",
                    "Слизь",
                    "Скрытень",
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 89,
                name = "Убежище синдиката",
                requirements = "Син-Ра",
                monsters = listOf(
                    "Разбойник-страж",
                    "Разбойник-лучница",
                    "Культист",
                    "Гигантская гадюка",
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 90,
                name = "Демонический портал",
                monsters = listOf(
                    "Земляной демон",
                    "Воздушный демон",
                    "Ночной демон",
                    "Оживший дух"
                ),
                location = "Река Змеиный поцелуй",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 91,
                name = "Дикая схватка",
                monsters = listOf(
                    "Разбойник-страж",
                    "Разбойник-лучница",
                    "Пещерный медведь",
                    "Оживший дух",
                    "Гончая",
                ),
                location = "Кинжальный лес",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 92,
                name = "Потасовка в переулке",
                requirements = "Возвращение долга",
                monsters = listOf(
                    "Разбойник-страж",
                    "Разбойник-лучница",
                    "Городской страж",
                    "Городской лучник",
                    "Земляной демон",
                    "Огненный демон",
                    "Инокс-стражница",
                    "Саввас Поток лавы"
                ),
                location = "Мрачная гавань",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 93,
                name = "Затонувшее судно",
                requirements = "Карта сокровищ",
                monsters = listOf(
                    "Скрытень",
                    "Морозный демон",
                    "Оживший дух",
                ),
                location = "Туманное море",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 94,
                name = "Жилище вермлингов",
                newScenarios = "95",
                teamAchievement = "Путь через жилище",
                monsters = listOf(
                    "Пещерный медведь",
                    "Гончая",
                    "Вермлинг-разведчик",
                    "Вермлинг-шаман",
                ),
                location = "Мертволесье",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 95,
                name = "Час расплаты",
                requirements = "Путь через жилище",
                monsters = listOf(
                    "Земляной демон",
                    "Огненный демон",
                    "Невыносимый ужас",
                    "Саввас Поток лавы"
                ),
                location = "Мертволесье",
                pack = PackType.MAIN.name,
            ),
            ScenarioBd(
                scenarioNumber = 96,
                name = "Неожиданные посетители",
                requirements = "Конец эпохи Мрака",
                monsters = listOf(
                    "Земляной демон",
                    "Огненный демон",
                    "Морозный демон",
                    "Воздушный демон"
                ),
                location = "Мрачная гавань",
                newScenarios = "97",
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
            ScenarioBd(
                scenarioNumber = 97,
                newScenarios = "98, 99, 100, 101",
                name = "Утраченные знания",
                monsters = listOf(
                    "Черный бес",
                    "Ожившие кости",
                    "Оживший труп",
                    "Эстер-разведчик",
                    "Невыносимый ужас"
                ),
                location = "Перемещение между измерениями",
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
            ScenarioBd(
                scenarioNumber = 98,
                newScenarios = "",
                name = "Утраченные знания",
                monsters = listOf(
                    "Древняя пушка",
                    "Разбойник-лучница",
                    "Разбойник-страж",
                    "Шипящий дрейк",
                ),
                location = "Мрачная гавань",
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
            ScenarioBd(
                scenarioNumber = 99,
                name = "Отголоски прошлого",
                monsters = listOf(
                    "Черный бес",
                    "Культист",
                    "Невыносимый ужас",
                    "Валрат-варвар",
                ),
                location = "Перемещение между измерениями",
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
            ScenarioBd(
                scenarioNumber = 100,
                name = "Поворотный механизм",
                monsters = listOf(
                    "Каменный голем",
                    "Оживший дух",
                ),
                location = "Перемещение между измерениями",
                globalAchievement = "Знание-сила",
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
            ScenarioBd(
                scenarioNumber = 101,
                newScenarios = "108, 109",
                name = "Затопленный склеп",
                monsters = listOf(
                    "Когтистый дрейк",
                    "Шипящий дрейк",
                    "Ожившие кости",
                    "Оживший труп",
                ),
                location = "Перемещение между измерениями",
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
            ScenarioBd(
                scenarioNumber = 102,
                name = "Ярмарка знаний",
                requirements = "Знание-сила", // 2
                location = "Перемещение между измерениями",
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
            ScenarioBd(
                scenarioNumber = 103,
                requirements = "Знание-сила", // 2
                name = "Нужный момент",
                location = "Перемещение между измерениями",
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
            ScenarioBd(
                scenarioNumber = 104,
                requirements = "Знание-сила", // 2
                name = "Зияющая рана",
                location = "Перемещение между измерениями",
                monsters = listOf(
                    "Жнец заразитель",
                    "Скрытень",
                    "Солнечный демон",
                    "Шипящий дрейк",
                ),
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
            ScenarioBd(
                scenarioNumber = 105,
                requirements = "Знание-сила && !Охота на охотников", // 2
                name = "Ужасы культа",
                location = "Перемещение между измерениями",
                monsters = listOf(
                    "Разбойник-страж",
                    "Валрат-следопыт",
                    "Гончая",
                    "Валрат-варвар"
                ),
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
            ScenarioBd(
                scenarioNumber = 106,
                requirements = "Знание-сила", // 2
                name = "Причудливая конструкция",
                location = "Перемещение между измерениями",
                monsters = listOf(
                    "Эстер-разведчик",
                    "Древняя пушка",
                    "Земляной демон",
                    "Огненный демон",
                    "Саввас Поток лавы",
                    "Морозный демон",
                    "Воздушный демон",
                    "Саввас Ледяной шторм"
                ),
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
            ScenarioBd(
                scenarioNumber = 107,
                requirements = "Знание-сила", // 2
                name = "Гений механики",
                location = "Перемещение между измерениями",
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
            ScenarioBd(
                scenarioNumber = 108,
                requirements = "Знание-сила", // 2
                name = "Гений механики",
                location = "Перемещение между измерениями",
                monsters = listOf(
                    "Городской лучник",
                    "Городской страж",
                    "Полководец людей",
                    "Полководец валратов",
                    "Валрат-варвар",
                    "Валрат-следопыт",
                ),
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
            ScenarioBd(
                scenarioNumber = 109,
                requirements = "Знание-сила", // 2
                name = "Исход войны",
                location = "Перемещение между измерениями",
                monsters = listOf(
                    "Городской лучник",
                    "Городской страж",
                    "Валрат-варвар",
                    "Валрат-следопыт",
                ),
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),

            ScenarioBd(
                scenarioNumber = 110,
                name = "Замкнутый круг",
                location = "Перемещение между измерениями",
                monsters = listOf(
                    "Земляной демон",
                    "Стальной лев",
                    "Огненный демон",
                    "Уйрат Иккума",
                    "Села Наберис",
                    "Шрака мудрый",
                ),
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),

            ScenarioBd(
                scenarioNumber = 111,
                name = "Сброщенные оковы",
                location = "Мрачная гавань",
                monsters = listOf(
                    "Эстер Пепельный клинок",
                    "Эстер-разведчик",
                    "Черный бес",
                    "Ночной демон",
                    "Шелуха",
                ),
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),

            ScenarioBd(
                scenarioNumber = 112,
                name = "Основа основ",
                location = "Перемещение между измерениями",
                monsters = listOf(
                    "Древняя пушка",
                    "Ожившие кости ",
                    "Каменный голем",
                ),
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),

            ScenarioBd(
                scenarioNumber = 113,
                name = "Потерянный след",
                location = "Перемещение между измерениями",
                monsters = listOf(
                    "Каменный голем",
                ),
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),

            ScenarioBd(
                scenarioNumber = 114,
                name = "Хрупкое равновесие",
                location = "Мрачная гавань",
                monsters = listOf(
                    "Эстер Пепельный клинок",
                    "Эстер-разведчик",
                ),
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),

            ScenarioBd(
                scenarioNumber = 115,
                name = "Будущее туманно",
                location = "Перемещение между измерениями",
                pack = PackType.FORGOTTEN_CIRCLES.name,
            ),
        )
    }
}